### ISSUE TITLE
Support for other private key types and bits

### ISSUE THREAD

**Issue by willfarrell** [ntrippar/sekey#15]
- [ ] ed25512 w/ option to change rounds
- [ ] ecdsa {384,512}
- [ ] rsa {2048,4096}

Samples on how I create the above now:
```bash
ssh-keygen -q -t ed25519 -o -a 100 -N '' -C "will Farrell's MacBook Pro" -f ~/.ssh/id_ed25512
ssh-keygen -q -t rsa -b 4096 -N '' -C "will Farrell's MacBook Pro" -f ~/.ssh/id_rsa
ssh-keygen -q -t ecdsa -b 521 -N '' -C "will Farrell's MacBook Pro" -f ~/.ssh/id_ecdsa
```
[manpage](https://linux.die.net/man/1/ssh-keygen) - matching the arguments might be helpful to most users.

**Comment by ntrippar** [comment]
The main issue of how this works is that the private key is never on your computer. and the secure enclave has limitations only to generate this type of elliptic curves key. what we could do is generating normal keys and store in the keychain (but is not going to be that secure). because the keys will be decrypted on memory.

**Comment by willfarrell** [comment]
Oh okay, that makes sense why it's not an option already. That's a bummer. I know popular services like bitbucket only support RSA, was really hoping to use this for all my ssh needs.

I did a little research and found doc that mention it, thought others might run across this and ask the same question.
https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/storing_keys_in_the_secure_enclave
