### ISSUE TITLE
Locked out of Authentication

### ISSUE THREAD

**Issue by Rudi9719** [ntrippar/sekey#7]
If you have too many keys stored, SSHD will lock you out because you offer each key, is there a way to only supply a specific key for each host?

**Comment by ntrippar** [comment]
i have a ticket planning to add a feature to enable/disable keys. how the ssh-agent works (as far i research it) and you can see in this code https://github.com/ntrippar/ssh-agent/blob/master/src/protocol.rs#L88 and in the RFC https://tools.ietf.org/html/draft-miller-ssh-agent-00 the ssh don't send where the communication came from. i will try in some way to fix this (also because every time you are connecting to a server you are leaking all your public keys)

**Comment by piger** [comment]
@Rudi9719 I believe what you want is `IdentitiesOnly=yes` and set `IdentityFile` for each host in your `ssh_config` file; see https://superuser.com/questions/268776/how-do-i-configure-ssh-so-it-dosent-try-all-the-identity-files-automatically
